// Datos temporales del menu. App.js usa este arreglo para pintar las tarjetas.
const menuItems = [
  {
    id: "ceviche-caribe",
    nombre: "Ceviche Caribe temporal",
    descripcion: "Pescado fresco, lim\u00f3n, pepino, cebolla morada y mango.",
    precio: 145,
    categoria: "Ceviches",
    imagen: "assets/images/products/ceviche-acapulco.png",
    disponible: true,
  },
  {
    id: "ceviche-mixto",
    nombre: "Ceviche mixto temporal",
    descripcion: "Camaron, pescado, pulpo, cilantro y salsa de la casa.",
    precio: 172,
    categoria: "Ceviches",
    imagen: "assets/images/products/ceviche-acapulco.png",
    disponible: true,
  },
  {
    id: "ceviche-verde",
    nombre: "Ceviche verde temporal",
    descripcion: "Pescado en lim\u00f3n con aguacate, pepino y chile serrano.",
    precio: 158,
    categoria: "Ceviches",
    imagen: "assets/images/products/ceviche-acapulco.png",
    disponible: true,
  },
  {
    id: "tostada-atun",
    nombre: "Tostada de atun temporal",
    descripcion: "Atun sellado, aguacate, ajonjoli y salsa citrica.",
    precio: 98,
    categoria: "Tostadas",
    imagen: "assets/images/products/tostada-pulpo.png",
    disponible: true,
  },
  {
    id: "tostada-camaron",
    nombre: "Tostada de camaron temporal",
    descripcion: "Camaron fresco, pico de gallo, aguacate y mayonesa ligera.",
    precio: 92,
    categoria: "Tostadas",
    imagen: "assets/images/products/tostada-pulpo.png",
    disponible: true,
  },
  {
    id: "tostada-pulpo",
    nombre: "Tostada de pulpo temporal",
    descripcion: "Pulpo marinado, chile tatemado, cebolla morada y cilantro.",
    precio: 115,
    categoria: "Tostadas",
    imagen: "assets/images/products/tostada-pulpo.png",
    disponible: true,
  },
  {
    id: "coctel-camaron",
    nombre: "Coctel de camaron temporal",
    descripcion: "Camaron, jitomate, cilantro, aguacate y salsa coctelera.",
    precio: 165,
    categoria: "Cocteles",
    imagen: "assets/images/products/coctel-camaron.png",
    disponible: true,
  },
  {
    id: "coctel-vuelve",
    nombre: "Vuelve a la vida temporal",
    descripcion: "Mezcla de mariscos, jugo coctelero, aguacate y lim\u00f3n.",
    precio: 195,
    categoria: "Cocteles",
    imagen: "assets/images/products/coctel-camaron.png",
    disponible: true,
  },
  {
    id: "aguachile-verde",
    nombre: "Aguachile verde temporal",
    descripcion: "Camaron fresco, chile serrano, lim\u00f3n, pepino y cebolla.",
    precio: 178,
    categoria: "Especialidades",
    imagen: "assets/images/products/tacos-gobernador.png",
    disponible: true,
  },
  {
    id: "tacos-pescado",
    nombre: "Tacos de pescado temporal",
    descripcion: "Pescado crujiente, col morada, crema de chipotle y lim\u00f3n.",
    precio: 132,
    categoria: "Especialidades",
    imagen: "assets/images/products/tacos-gobernador.png",
    disponible: true,
  },
  {
    id: "arroz-mariscos",
    nombre: "Arroz costero temporal",
    descripcion: "Arroz con camaron, pulpo, vegetales y especias costeras.",
    precio: 185,
    categoria: "Especialidades",
    imagen: "assets/images/products/guacamole-costero.png",
    disponible: true,
  },
  {
    id: "agua-limon",
    nombre: "Agua de lim\u00f3n temporal",
    descripcion: "Agua fresca de lim\u00f3n con hierbabuena y hielo.",
    precio: 38,
    categoria: "Bebidas",
    imagen: "assets/images/products/agua-jamaica.png",
    disponible: true,
  },
  {
    id: "agua-jamaica",
    nombre: "Agua de jamaica temporal",
    descripcion: "Infusi\u00f3n de jamaica servida fr\u00eda con toque c\u00edtrico.",
    precio: 38,
    categoria: "Bebidas",
    imagen: "assets/images/products/agua-jamaica.png",
    disponible: true,
  },
  {
    id: "agua-pepino",
    nombre: "Agua de lim\u00f3n pepino",
    descripcion: "Infusi\u00f3n de lim\u00f3n y pepino servida fr\u00eda con toque de ch\u00eda.",
    precio: 38,
    categoria: "Bebidas",
    imagen: "assets/images/products/agua-jamaica.png",
    disponible: true,
  },
  {
    id: "refresco",
    nombre: "Refresco temporal",
    descripcion: "Refresco fr\u00edo de lata para acompa\u00f1ar tus mariscos.",
    precio: 32,
    categoria: "Bebidas",
    imagen: "assets/images/products/agua-jamaica.png",
    disponible: true,
  },
];
